<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>Top.Assets.Contract</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Top.Gltf\Top.Gltf.csproj" />
    <ProjectReference Include="..\Top.Logging\Top.Logging.csproj" />
  </ItemGroup>
</Project>
