namespace Top.Tables.Records
{
    public enum ItemType
    {
        Sword = 1,
        Glave = 2,
        Bow = 3,
        Harquebus = 4,
        Falchion = 5,
        Mitten = 6,
        Stylet = 7,
        Moneybag = 8,
        Cosh = 9,
        Sinker = 10,
        Shield = 11,
        Arrow = 12,
        Ammo = 13,
        Headpiece = 19,
        Hair = 20,
        Face = 21,
        Clothing = 22,
        Glove = 23,
        Boot = 24,
        Necklace = 25,
        Ring = 26,
        Tattoo = 27,
        Conch = 29,
        Medicine = 31,
        Ovum = 32,
        UnknownConsumable = 33,
        Scroll = 36,
        General = 41,
        Mission = 42,
        Boat = 43,
        Wing = 44,
        Trade = 45,
        Bravery = 46,
        Hull = 51,
        Embolon = 52,
        Engine = 53,
        Artillery = 54,
        Airscrew = 55,
        BoatSign = 56,
        PetFodder = 57,
        PetSock = 58,
        Pet = 59,
        Cloak = 88,
        Mount = 90,
        LotteryTicket = 99,
    }

    public enum ItemPickTo
    {
        Kitbag = 0,
        Cabin = 1,
    }

    public class ItemInfoRecord : TableRecord
    {
        public string Icon;
        public string[] Modules;
        public int ShipFlag;
        public int ShipType;
        public ItemType Type;
        public int ForgeLevel;
        public int ForgeSteady;
        public bool HasExclusiveId;
        public bool Tradeable;
        public bool Pickable;
        public bool Discardable;
        public bool Deletable;
        public int PileMax;
        public bool Instanced;
        public int Price;
        public int[] Body;
        public int NeedLevel;
        public int[] Jobs;
        public int[] EquipSlots;
        public int[] NeedSlots;
        public ItemPickTo PickTo;
        public int StrengthCoef;
        public int AgilityCoef;
        public int AccuracyCoef;
        public int ConstitutionCoef;
        public int SpiritCoef;
        public int LuckCoef;
        public int AttackSpeedCoef;
        public int AttackDistanceCoef;
        public int MinAttackCoef;
        public int MaxAttackCoef;
        public int DefenseCoef;
        public int MaxHpCoef;
        public int MaxSpCoef;
        public int DodgeCoef;
        public int HitCoef;
        public int CriticalCoef;
        public int MagicFindCoef;
        public int HpRecoveryCoef;
        public int SpRecoveryCoef;
        public int MoveSpeedCoef;
        public int CollectCoef;
        public int[] StrengthValue;
        public int[] AgilityValue;
        public int[] AccuracyValue;
        public int[] ConstitutionValue;
        public int[] SpiritValue;
        public int[] LuckValue;
        public int[] AttackSpeedValue;
        public int[] AttackRangeValue;
        public int[] MinAttackValue;
        public int[] MaxAttackValue;
        public int[] DefenseValue;
        public int[] MaxHpValue;
        public int[] MaxSpValue;
        public int[] DodgeValue;
        public int[] HitValue;
        public int[] CriticalValue;
        public int[] MagicFindValue;
        public int[] HpRecoveryValue;
        public int[] SpRecoveryValue;
        public int[] MoveSpeedValue;
        public int[] CollectValue;
        public int[] PhysicalResist;
        public int LeftHandValue;
        public int[] Energy;
        public int[] Endure;
        public int Holes;
        public string AttrEffect;
        public int Drap;
        public int[] BindEffects;
        public int[] BindEffectDummies;
        public int[] ItemEffect;
        public int[] AreaEffect;
        public int[] UseItemEffect;
        public string Description;
        public float Cooldown;
    }
}
